### ISSUE TITLE
probleme de traduction

### ISSUE THREAD

**Issue by tetre88** [lakadev/jarvis-translate#1]
bonjours j'ai un petit probleme ^^ le plugin marche vu que quand je lui demande en quel langue il peut traduire il me repond mais quand je demande une traduction ca me donne ceci:

monsieur: traduis bleu en anglais
jarvis: Alors, si je me souviens bien...
jarvis: "bleu" se dit en anglais :
??

biensur j'ai rentrer ma cle "translator speech api" merci de votre aide :)

**Comment by lakadev** [comment]
Bonjour,

Le fait d'avoir la liste des langues suportées n'implique pas que la traduction fonctionne. C'est une liste qui est en fait déjà incluse dans le plugin qui est affichée.

J'arrive à reproduire ce comportement du "??" en utilisant une clef Microsoft Translator invalide.
Il faut donc vérifier la saisie de la clef. J'ai eu un problème similaire récement avec une clef Google Speech, avec des inversions de 'L' minuscule et de 'I' majuscule.

**Comment by tetre88** [comment]
y devrait pas y avoir de probleme j'ai copier/coller la clef, j ai meme reinitiliser plusieurs fois les clefs qui me donne

**Comment by tetre88** [comment]
en effet microsoft avait une erreur dans ces clef mais maintenant ca ne marche que en mode clavier :/

**Comment by lakadev** [comment]
Ok.
Par contre pour le mode clavier c'est peu probable que cela soit lié au plugin.
Il faudrait tenter de relancer l'assistant de réglage audio de Jarvis.
Je ferme ce ticket-ci pour ne pas mélanger les sujets.
Merci.
